stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/ai4i2020.csv
    outs:
    - data/raw/ai4i2020.csv
  
  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/ai4i2020.csv
    outs:
    - data/processed/train_ai4i2020.csv
    - data/processed/test_ai4i2020.csv 